import React from 'react';
import Week from './Week';

const weeksToDisplay = 6;

const Month = ({date}) => {
    // based off of the passed month, generate 6 weeks worth of days
    // from the sunday of the first week of a month.
    let firstSunday = new Date(date.getFullYear(), date.getMonth());
    firstSunday.setDate(-1 * firstSunday.getDay() + 1);
    
    // Generate $weeksToDisplay number of sundays to create weeks
    let sundays = [];
    for (let i = 0; i < (weeksToDisplay); i++) {
        let item = new Date(firstSunday);
        sundays.push(item);
        firstSunday.setDate(firstSunday.getDate() + 7);
    }
    
    let weeks = sundays.map(sunday => {
        return <Week currentMonth={date.getMonth()} sunday={sunday} key={"-week" + sunday.toISOString()}/>
    })

    return (
        <tbody>
            {/* Every <tr> is generated by Week.js */}
            {weeks}
        </tbody>
    );
}
 
export default Month;